version: '3.8'

services:
  deno-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - DENO_DIR=/usr/src/app/cache